# Generated by Django 5.1.4 on 2024-12-12 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("descrition", models.TextField(blank=True, null=True)),
                (
                    "start_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="日時"),
                ),
                ("duration", models.DurationField(verbose_name="作業時間")),
                (
                    "category",
                    models.CharField(
                        choices=[("English", "英語"), ("ComputerScience", "情報")],
                        max_length=100,
                        verbose_name="カテゴリ",
                    ),
                ),
            ],
        ),
    ]
