# Generated by Django 5.1.4 on 2025-01-09 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="titlerecord",
            name="title",
            field=models.CharField(default=1, max_length=100, verbose_name="タスク名"),
            preserve_default=False,
        ),
    ]
