# Generated by Django 5.1.4 on 2025-02-04 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("timer", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studyrecord",
            name="category",
        ),
    ]
