# Generated by Django 5.1.4 on 2024-12-12 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("timer", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Record",
            new_name="StudyRecord",
        ),
    ]
