# Generated by Django 5.1.4 on 2025-01-27 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("timer", "0002_titlerecord_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studyrecord",
            name="category",
        ),
    ]
