# Generated by Django 5.1.4 on 2024-12-12 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timer", "0002_rename_record_studyrecord"),
    ]

    operations = [
        migrations.CreateModel(
            name="DurationChoices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("duration", models.DurationField()),
            ],
        ),
        migrations.AlterField(
            model_name="studyrecord",
            name="duration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="timer.durationchoices",
                verbose_name="作業時間",
            ),
        ),
    ]
