# Generated by Django 5.1.4 on 2025-01-28 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("timer", "0004_studyrecord_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studyrecord",
            name="user",
        ),
    ]
