# Generated by Django 5.1.4 on 2025-01-28 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timer", "0005_remove_studyrecord_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="studyrecord",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="timer.categoryrecord",
            ),
            preserve_default=False,
        ),
    ]
