# Generated by Django 5.1.4 on 2025-01-28 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("timer", "0006_studyrecord_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studyrecord",
            name="category",
        ),
    ]
